// Code generated manually for v2raya-core.
// source: hint/app/observatory/compat/config.proto
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package compat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

// CompatConfig is a marker config type that enables the v2ray-compatible
// observatory gRPC service when included in the commander's service list.
type CompatConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompatConfig) Reset() {
	*x = CompatConfig{}
	mi := &file_hint_app_observatory_compat_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *CompatConfig) String() string  { return protoimpl.X.MessageStringOf(x) }
func (*CompatConfig) ProtoMessage()      {}

func (x *CompatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_hint_app_observatory_compat_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CompatConfig) Descriptor() ([]byte, []int) {
	return file_hint_app_observatory_compat_config_proto_rawDescGZIP(), []int{0}
}

var (
	file_hint_app_observatory_compat_config_proto_rawDescOnce sync.Once
	file_hint_app_observatory_compat_config_proto_rawDescData []byte
)

func file_hint_app_observatory_compat_config_proto_rawDescGZIP() []byte {
	file_hint_app_observatory_compat_config_proto_rawDescOnce.Do(func() {
		file_hint_app_observatory_compat_config_proto_rawDescData =
			file_hint_app_observatory_compat_config_proto_rawDesc
	})
	return file_hint_app_observatory_compat_config_proto_rawDescData
}

// rawDesc is the proto FileDescriptorProto for this package.
// Generated by encoding:
//   syntax = "proto3";
//   package v2raya.core.hint.app.observatory.compat;
//   option go_package = "github.com/v2rayA/v2raya-core/hint/app/observatory/compat";
//   message CompatConfig {}
var file_hint_app_observatory_compat_config_proto_rawDesc = []byte{
	0x0a, 0x28, 0x68, 0x69, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x27, 0x76, 0x32, 0x72, 0x61,
	0x79, 0x61, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x68, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x76, 0x32, 0x72, 0x61, 0x79, 0x41, 0x2f, 0x76, 0x32, 0x72, 0x61, 0x79, 0x61, 0x2d,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x68, 0x69, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hint_app_observatory_compat_config_proto_goTypes    = []any{(*CompatConfig)(nil)}
	file_hint_app_observatory_compat_config_proto_depIdxs    = []int32{0, 0, 0, 0}
	file_hint_app_observatory_compat_config_proto_msgTypes   = make([]protoimpl.MessageInfo, 1)
	File_hint_app_observatory_compat_config_proto            protoreflect.FileDescriptor
)

func init() { file_hint_app_observatory_compat_config_proto_init() }

func file_hint_app_observatory_compat_config_proto_init() {
	if File_hint_app_observatory_compat_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hint_app_observatory_compat_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hint_app_observatory_compat_config_proto_goTypes,
		DependencyIndexes: file_hint_app_observatory_compat_config_proto_depIdxs,
		MessageInfos:      file_hint_app_observatory_compat_config_proto_msgTypes,
	}.Build()
	File_hint_app_observatory_compat_config_proto = out.File
	file_hint_app_observatory_compat_config_proto_goTypes = nil
	file_hint_app_observatory_compat_config_proto_depIdxs = nil
}
